apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker #Change this to the appropriate role if needed
  name: 99-worker-nonrotational-udev-configuration
spec:
  config:
    ignition:
      config: {}
      security:
        tls: {}
      timeouts: {}
      version: 2.2.0
    networkd: {}
    passwd: {}
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,QUNUSU9OPT0iYWRkfGNoYW5nZSIsIFNVQlNZU1RFTT09ImJsb2NrIiwgS0VSTkVMPT0ic2RbYS16XSIsICBBVFRSe3F1ZXVlL3JvdGF0aW9uYWx9PSIwIgo=
          verification: {}
        filesystem: root
        mode: 420
        path: /etc/udev/rules.d/99-nonrotational.rules
  osImageURL: ""
